num_motion: 12

# arm ee = -2; com = -1;
motion0:
  ee: [-2]  ## arm motion
  pos: [0.5,0.5,0.05]
  ori: [1,0,0,0]
  periods: [0.0, 10.0]
  b_relative: true

motion1:
  ee: [-1] ## com motion
  pos: [0.05,0.05,-0.05]
  ori: [1,0,0,0]
  periods: [0.0, 2.0]
  b_relative: true

motion2:
  ee: [-1] ## com motion
  pos: [0.2,0.2,0.1]
  ori: [1,0,0,0]
  periods: [2.0, 6.0]
  b_relative: true

motion3:
  ee: [-1] ## com motion
  pos: [0.2,0.2,0.1]
  ori: [1,0,0,0]
  periods: [6.0, 10.0]
  b_relative: true

# LF = 0; LH = 1; RF = 2; RH = 3;
motion4:
  ee: [0] ## 
  pos: [0.0, 0.05, 0.0]
  ori: [1, 0, 0, 0]
  periods: [0.5, 2.0]
  b_relative: true

motion5:
  ee: [1, 3] ## 
  pos: [0.0, 0.0, 0.0]
  ori: [1, 0, 0, 0]
  periods: [1.5, 2.4]
  b_relative: true

motion6:
  ee: [0, 1] ## 
  pos: [0.1, 0.1, 0.0]
  ori: [1, 0, 0, 0]
  periods: [2.5, 3.4]
  b_relative: true

motion7:
  ee: [2, 3] ## 
  pos: [0.1, 0.1, 0.0]
  ori: [1, 0, 0, 0]
  periods: [3.5, 4.4]
  b_relative: true

motion8:
  ee: [0, 3] ## 
  pos: [0.05, 0.05, 0.0]
  ori: [1, 0, 0, 0]
  periods: [3.5, 4.4]
  b_relative: true

motion9:
  ee: [1, 2] ## 
  pos: [0.05, 0.05, 0.0]
  ori: [1, 0, 0, 0]
  periods: [4.5, 5.4]
  b_relative: true

motion10:
  ee: [0, 3] ## 
  pos: [0.05, 0.05, 0.0]
  ori: [1, 0, 0, 0]
  periods: [5.5, 6.4]
  b_relative: true

motion11:
  ee: [1, 2] ## 
  pos: [0.05, 0.05, 0.0]
  ori: [1, 0, 0, 0]
  periods: [6.5, 7.4]
  b_relative: true