num_motion: 3

# LF = 0; LH = 1; RF = 2; RH = 3;
motion0:
  ee: [-1] ## 
  pos: [-0.05, -0.05, 0.0]
  ori: [1, 0, 0, 0]
  periods: [0.0, 0.6]
  b_relative: true

motion1:
  ee: [-1] ## 
  pos: [0.1, 0.1, 0.0]
  ori: [1, 0, 0, 0]
  periods: [1.0, 2.0]
  b_relative: true

motion2:
  ee: [0] ## 
  pos: [0.1, 0.0, 0.0]
  ori: [1, 0, 0, 0]
  periods: [0.5, 1.5]
  b_relative: true

motion3:
  ee: [1, 2] ## 
  pos: [0.0, 0.0, 0.0]
  ori: [1, 0, 0, 0]
  periods: [7.0, 10.0]
  b_relative: true
