num_motion: 4
type_motion: 1 # 0:climbing, 1:walking, 2:balancing

motion0:
  foot: 2
  pos: [-0.1,0,0]
  ori: [1,0,0,0]
  durations: [0.4, 0.1, 0.4, 0.1]
  swing_height: 0.05
  b_relative: true

motion1:
  foot: 0
  pos: [-0.1,0,0]
  ori: [1,0,0,0]
  durations: [0.4, 0.1, 0.4, 0.1]
  swing_height: 0.05
  b_relative: true

motion2:
  foot: 3
  pos: [-0.1,0,0]
  ori: [1,0,0,0]
  durations: [0.4, 0.1, 0.4, 0.1]
  swing_height: 0.05
  b_relative: true

motion3:
  foot: 1
  pos: [-0.1,0,0]
  ori: [1,0,0,0]
  durations: [0.4, 0.1, 0.4, 0.1]
  swing_height: 0.05
  b_relative: true






