num_motion: 5
# foot : AL-8/14, AR-17/23, BL-26/32 , BR-35/41

motion0:
  pos: [0,0,-0.01]
  ori: [1,0,0,0]
  duration: 0.4
  b_relative: false

motion1:
  pos: [-0.02, 0.0, 0.02]
  ori: [1,0,0,0]
  duration: 1
  b_relative: true

motion2:
  pos: [0.04, 0.02, -0.02]
  ori: [1,0,0,0]
  duration: 1
  b_relative: true

motion3:
  pos: [-0.04, 0.0, 0.02]
  ori: [1,0,0,0]
  duration: 1
  b_relative: true

motion4:
  pos: [0.02, -0.02, -0.02]
  ori: [1,0,0,0]
  duration: 1
  b_relative: true




