num_motion: 5

motion0:
  pos: [0,0,-0.015]
  ori: [1,0,0,0]
  duration: 0.15
  b_relative: true

motion1:
  pos: [0.02, 0.02, 0.0]
  ori: [1,0,0,0]
  duration: 1
  b_relative: true

motion2:
  pos: [-0.03, -0.03, 0.0]
  ori: [1,0,0,0]
  duration: 1.5
  b_relative: true

motion3:
  pos: [0.01, 0.01, 0.01]
  ori: [1,0,0,0]
  duration: 1
  b_relative: true

motion4:
  pos: [0.0, 0.0, -0.02]
  ori: [1,0,0,0]
  duration: 1
  b_relative: true
