num_motion: 4
type_motion: 0 # 0:climbing, 1:walking, 2:balancing

# foot : AL-0, AR-1, BL-2, BR-3
# frame : base-0, foot-1

motion0:
  foot: 1
  pos: [-0.1,0,0]
  ori: [1,0,0,0]
  swing_height: 0.05
  duration: 0.25
  frame: 0
  # for only simulation
  mu: 0.3 # friction
  fm: 40 # adhesive force

motion1:
  foot: 2
  pos: [-0.1,0,0]
  ori: [1,0,0,0]
  swing_height: 0.05
  duration: 0.25
  frame: 0
  # for only simulation
  mu: 0.5 # friction
  fm: 70 # adhesive force

motion2:
  foot: 3
  pos: [-0.1,0,0]
  ori: [1,0,0,0]
  swing_height: 0.05
  duration: 0.25
  frame: 0
  # for only simulation
  mu: 0.5 # friction
  fm: 70 # adhesive force

motion3:
  foot: 0
  pos: [-0.1,0,0]
  ori: [1,0,0,0]
  swing_height: 0.05
  duration: 0.25
  frame: 0
  # for only simulation
  mu: 0.5 # friction
  fm: 70 # adhesive force