num_motion: 4
type_motion: 0 # 0:climbing, 1:walking, 2:balancing

# foot : AL-0, AR-1, BL-2, BR-3
# frame : base-0, foot-1

motion0:
  foot: 2
  pos: [-0.1,0,0]
  ori: [1,0,0,0]
  swing_height: 0.05
  duration: 0.4  
  frame: 0
  new_contact_spec: [0.7, 100] # for only simulation [mu, adhesion]

motion1:
  foot: 0
  pos: [-0.1,0,0]
  ori: [1,0,0,0]
  swing_height: 0.05
  duration: 0.4  
  frame: 0
  new_contact_spec: [0.7, 100] # for only simulation [mu, adhesion]

motion2:
  foot: 3
  pos: [-0.1,0,0]
  ori: [1,0,0,0]
  swing_height: 0.05
  duration: 0.4  
  frame: 0
  new_contact_spec: [0.7, 100] # for only simulation [mu, adhesion]

motion3:
  foot: 1
  pos: [-0.1,0,0]
  ori: [1,0,0,0]
  swing_height: 0.05
  duration: 0.4  
  frame: 0
  new_contact_spec: [0.7, 100] # for only simulation [mu, adhesion]