num_motion: 5 #4
type_motion: 0 # 0:climbing, 1:walking, 2:balancing

# foot : AL-0, AR-1, BL-2, BR-3
# frame : base-0, foot-1

motion0:
  foot: 1
  pos: [-0.07,0,0]
  ori: [1,0,0,0]
  swing_height: 0.03
  durations: [0.3, 0.05, 0.25, 0.1]
  frame: 0
  # for only simulation
  mu: 0.7 # friction
  fm: 75 # adhesive force

motion1:
  foot: 2
  pos: [-0.07,0,0]
  ori: [1,0,0,0]
  swing_height: 0.03
  durations: [0.3, 0.05, 0.25, 0.1]
  frame: 0
  # for only simulation
  mu: 0.7 # friction
  fm: 75 # adhesive force

motion2:
  foot: 3
  pos: [-0.07,0,0]
  ori: [1,0,0,0]
  swing_height: 0.03
  durations: [0.3, 0.05, 0.25, 0.1]
  frame: 0
  # for only simulation
  mu: 0.7 # friction
  fm: 75 # adhesive force

motion3:
  foot: 0
  pos: [-0.07,0,0]
  ori: [1,0,0,0]
  swing_height: 0.03
  durations: [0.3, 0.05, 0.25, 0.1]
  frame: 0
  # for only simulation
  mu: 0.7 # friction
  fm: 75 # adhesive force

motion4:
  foot: 1
  pos: [-0.07,0,0]
  ori: [1,0,0,0]
  swing_height: 0.03
  durations: [0.3, 0.05, 0.25, 0.1]
  frame: 0
  # for only simulation
  mu: 0.7 # friction
  fm: 75 # adhesive force

motion5:
  foot: 2
  pos: [-0.07,0,0]
  ori: [1,0,0,0]
  swing_height: 0.03
  durations: [0.3, 0.05, 0.25, 0.1]
  frame: 0
  # for only simulation
  mu: 0.7 # friction
  fm: 75 # adhesive force

motion6:
  foot: 3
  pos: [-0.07,0,0]
  ori: [1,0,0,0]
  swing_height: 0.03
  durations: [0.3, 0.05, 0.25, 0.1]
  frame: 0
  # for only simulation
  mu: 0.7 # friction
  fm: 75 # adhesive force

motion7:
  foot: 0
  pos: [-0.07,0,0]
  ori: [1,0,0,0]
  swing_height: 0.03
  durations: [0.3, 0.05, 0.25, 0.1]
  frame: 0
  # for only simulation
  mu: 0.7 # friction
  fm: 75 # adhesive force
