num_motion: 4
# foot : AL-8/14, AR-17/23, BL-26/32 , BR-35/41

motion0:
  foot: 8
  pos: [-0.1,0,0]
  ori: [1,0,0,0]
  duration: 1.9
  b_relative: true

motion1:
  foot: 17
  pos: [-0.1,0,0]
  ori: [1,0,0,0]
  duration: 1.9
  b_relative: true

motion2:
  foot: 26
  pos: [-0.1,0,0]
  ori: [1,0,0,0]
  duration: 1.9
  b_relative: true

motion3:
  foot: 35
  pos: [-0.1,0,0]
  ori: [1,0,0,0]
  duration: 1.9
  b_relative: true





