num_motion: 4
type_motion: 1 # 0:climbing, 1:walking, 2:balancing

# foot : AL-8/14, AR-17/23, BL-26/32 , BR-35/41: link_3/link

motion1:
  foot: 32 # 26 #BL
  pos: [-0.1,0,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.05
  b_relative: true

motion3:
  foot: 41 #35 #BR
  pos: [-0.1,0,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.05
  b_relative: true

motion0:
  foot: 14 #8 #AL
  pos: [-0.1,0,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.05
  b_relative: true

motion2:
  foot: 23 #17 #AR
  pos: [-0.1,0,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.05
  b_relative: true






