controller_params:
    #0:MRWBCC, #1:MFWBCC
    wbc_type: 0
    # Enable torque limits
    enable_torque_limits: true
    torque_limit: 5 #4.5
    # WBC pd gain
    kp: [ 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20]
    kd: [ 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3 ]
    # Integration_parameters
    velocity_freq_cutoff: 2.0 #Hz
    position_freq_cutoff: 1.0 #Hz
    max_position_error: 0.2 # radians

slip_observer_params:
    weight_shaping: 1 # onoff
    online_param_estimation: 0 #onoff
    slip_velocity_threshold: 0.005
    lpf_vel_cutoff: 30 #hz

contact_params:
    # AL,AR,BL,BR
    # friction: [0.5, 0.3, 0.5, 0.5]  
    # friction: [0.5, 0.5, 0.5, 0.5]    
    friction: [0.7, 0.7, 0.7, 0.7]

magnetism_params:
    # AL,AR,BL,BR
    magnetic_force: [100., 100., 100., 100.] #[N] 
    # magnetic_force: [80., 80., 80., 80.] #[N] 
    # magnetic_force: [70., 70., 70., 70.] #[N]   
    # magnetic_force: [75., 75., 75., 75.] #[N]
    # magnetic_force: [100., 100., 100., 100.] #[N]
    # residual_ratio: [5., 5., 5., 5.] #5 #[%]
    residual_ratio: [0., 0., 0., 0.] #5 #[%]

transition_params:
    transition_duration: 0.25

qp_weights_params:
    # max_rf_z: 150
    w_qddot: 1000. #1000
    w_xddot: 100.
    w_xddot_z_contact: 100
    w_xddot_z_nocontact: 0.001
    # w_xddot_nocontact: 0.001
    w_rf: 1.0
    w_rf_z_contact: 0.1 #0.01    
    w_rf_z_nocontact: 0.5 #0.5
    # w_rf_z: 0.01
    max_rf_z: 250
    max_rf_z_nocontact: 1

state_swing_params:
    swing_time_percent_early_contact_check: 0.5 # Percent of end_time to check if there are early contacts 
    early_contact_force_threshold: 10 # Exit swing when 10 Newtons have been detected on the foot contact sensor