# --simulator settings
servo_rate: 0.001 # !!this should be match with controller servo rate!!
is_record: false
show_joint_frame: false #false
show_link_frame: true #false
plot_mpc_result: false # true
plot_result: true # true

# --configuration settings
robot: robot_description/Robot/Magneto/MagnetoSim_Dart.urdf
ground: robot_description/Ground/magneto/ground_inclined03.urdf
initial_pose: [ 0.0, 0.0, 0.135, 0.0, 1.0, 0.0 ] # x,y,z, rx,ry,rz

# --motion script settings
#motion_script: Config/CSIRO/MOTIONS/balanceset.yaml
# motion_script: config/Magneto/MOTIONS/walkset.yaml
motion_script: config/Magneto/MOTIONS/climbset.yaml

# --controller settings
control_configuration:
  kp: 20 #35 #20 #300
  kd: 3 #3 #3 #15
  torque_limit: 5 #4.5

# -- initial physics settings
contact_params:
  # [AL, AR, BL, BR] >> MagnetoFoot @ MagnetoDefinition.hpp
  friction: [0.7, 0.7, 0.7, 0.7] 
  
magnetism_params:
  # [AL, AR, BL, BR] >> MagnetoFoot @ MagnetoDefinition.hpp
  magnetic_force: [147., 147., 147., 147.] #[N] 
  residual_magnetism: [0.0, 0.0, 0.0, 0.0] #5.0 # 3.0 #[%]